feat: separate login hooks
alfonsusac/devscale-eventmaker pull request #33
Opened 2024-02-03 15:40 UTC by rizaardiyanto1412

I put login hooks into separate files from the UI.

I confirmed this is works. You could test it with my login:

email: me@rizamaulana.com
password: 12345

2024-02-03 15:58 UTC, alfonsusac requested changes
move useLogin.jsx hook under the same file as LoginForm.jsx, below the component. 

The reason for this is that useLogin can only be used inside the LoginForm Component.

2024-02-03 16:35 UTC, rizaardiyanto1412 commented
@alfonsusac I put login func in lib/fetchApi.js as requested.

I confirm npm run build working fine.

2024-02-04 01:46 UTC, alfonsusac requested changes

2024-02-04 01:46 UTC, alfonsusac commented on src/lib/fetchAPI.js
> +      });
Hi, please only put this part into a `requestLogin()` function in /lib/fetchAPI.

The rest of the hook can be put inside `/LoginForm.jsx`

2024-02-04 02:58 UTC, alfonsusac requested changes

2024-02-04 02:58 UTC, alfonsusac commented on src/app/login/components/LoginForm.jsx
> +      <h1>LOGIN</h1>
There can't be more than one `<h1>`. Please change the other one into `<h2>`
Login text should be bigger than Eventmaker.

Thankss

2024-02-04 10:33 UTC, rizaardiyanto1412 commented
@alfonsusac I adjusted as required.

I added an Image as dummy logo to give you idea, instead of putting text, I'm proposing to add logo instead

2024-02-04 12:17 UTC, alfonsusac approved these changes

2024-02-04 12:17 UTC, alfonsusac commented on src/lib/fetchAPI.js
> +export { requestLogin };
Nice!

2024-02-04 12:17 UTC, alfonsusac commented on src/app/login/components/LoginForm.jsx
> +      const { payload, token } = await requestLogin(email, password);
NIce

2024-02-04 12:18 UTC, merged